require('jsongo21.options')
require('jsongo21.remap')

require('plugins.theme')
require('plugins.treesitter')
require('plugins.git')
require('plugins.telescope')
require('plugins.lsp')
require('plugins.editor')
require('plugins.lualine')
require('plugins.grapple')
require('plugins.which-key')
require('plugins.file-explorer')
